version: "3"
services:
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: rbac_db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
